#include "animal.h"
#include "animal.cpp"

#include "aqua.h"
#include "aqua.cpp"
#include "peste.h"
#include "peste.cpp"
#include "foca.h"
#include "foca.cpp"
#include "caracatita.h"
#include "caracatita.cpp"

#include "pasari.h"
#include "pasari.cpp"
#include "papagal.h"
#include "papagal.cpp"
#include "porumbel.h"
#include "porumbel.cpp"
#include "corb.h"
#include "corb.cpp"

#include "reptile.h"
#include "reptile.cpp"
#include "sarpe.h"
#include "sarpe.cpp"
#include "iguana.h"
#include "iguana.cpp"
#include "testoasa.h"
#include "testoasa.cpp"

#include "client.h"
#include "client.cpp"

#include "mamifere.h"
#include "mamifere.cpp"
#include "caine.h"
#include "caine.cpp"
#include "pisica.h"
#include "pisica.cpp"
#include "iepure.h"
#include "iepure.cpp"